//! Reusable ratatui pane framework.
//!
//! `tui_pane` provides the keymap, status bar, and built-in panes
//! (Keymap, Settings, Toasts) that an application embeds via the
//! `AppContext` trait.

mod activity;
mod app_context;
mod bar;
mod constants;
mod framework;
mod keymap;
mod layout;
mod overlays;
mod pane;
mod settings_store;
mod toasts;
mod util;
mod watched_file;

// Crate-root re-exports. The `action_enum!` and `bindings!` macros
// reference these types via `$crate::*` paths, which requires them at
// the crate root. `tests/macro_use.rs` locks the path stability.
pub use activity::ACTIVITY_SPINNER;
pub use activity::Icon;
pub use app_context::AppContext;
pub use app_context::NoToastAction;
pub use bar::BarPalette;
pub use bar::BarRegion;
pub use bar::BarSlot;
pub use bar::ShortcutState;
pub use bar::StatusBar;
pub use bar::StatusLine;
pub use bar::StatusLineGlobal;
pub use bar::Visibility;
pub use bar::render as render_status_bar;
pub use bar::render_status_line;
pub use bar::status_line_global_spans;
pub use constants::ACCENT_COLOR;
pub use constants::ACTIVE_BORDER_COLOR;
pub(crate) use constants::ACTIVE_FOCUS_COLOR;
pub use constants::BLOCK_BORDER_WIDTH;
pub use constants::BYTES_PER_GIB;
pub use constants::BYTES_PER_KIB;
pub use constants::BYTES_PER_MIB;
pub use constants::COLUMN_HEADER_COLOR;
pub use constants::DISCOVERY_SHIMMER_COLOR;
pub use constants::ERROR_COLOR;
pub use constants::FINDER_MATCH_BG;
pub use constants::FRAME_POLL_MILLIS;
pub use constants::HOVER_FOCUS_COLOR;
pub use constants::INACTIVE_BORDER_COLOR;
pub use constants::INACTIVE_TITLE_COLOR;
pub use constants::INLINE_ERROR_COLOR;
pub use constants::LABEL_COLOR;
pub(crate) use constants::REMEMBERED_FOCUS_COLOR;
pub use constants::SECONDARY_TEXT_COLOR;
pub use constants::SECTION_HEADER_INDENT;
pub use constants::SECTION_ITEM_INDENT;
pub use constants::STATUS_BAR_COLOR;
pub use constants::SUCCESS_COLOR;
pub use constants::TARGET_BENCH_COLOR;
pub use constants::TITLE_COLOR;
pub(crate) use framework::CycleDirection;
pub use framework::Framework;
pub use framework::FrameworkHit;
pub use framework::HitTestRegistry;
pub use framework::Hittable;
pub use framework::InputContext;
pub use framework::ListNavigation;
pub use framework::PaneRegistry;
pub use framework::Renderable;
pub use framework::TabStop;
pub use framework::clear_all_hover;
pub use framework::dispatch_hit_test;
pub use framework::render_panes;
pub use keymap::Action;
pub use keymap::Bindings;
pub use keymap::Configuring;
pub use keymap::GlobalAction;
pub use keymap::Globals;
pub use keymap::KeyBind;
pub use keymap::KeyOutcome;
pub(crate) use keymap::KeyParseError;
pub use keymap::Keymap;
pub use keymap::KeymapBuilder;
pub use keymap::KeymapError;
pub use keymap::Navigation;
pub use keymap::ScopeMap;
pub use keymap::Shortcuts;
pub use keymap::VimMode;
pub use layout::ColumnSpec;
pub use layout::ColumnWidths;
pub use layout::PaneAxisSize;
pub use layout::PaneGridLayout;
pub use layout::PanePlacement;
pub use layout::PaneSizeSpec;
pub use layout::ResolvedPane;
pub use layout::ResolvedPaneLayout;
pub use layout::Viewport;
pub use layout::ViewportOverflow;
pub use layout::constraints_for_sizes;
pub use layout::render_overflow_affordance;
pub use overlays::KeymapCaptureCommand;
pub use overlays::KeymapPane;
pub use overlays::KeymapPaneAction;
pub use overlays::SettingsCommand;
pub use overlays::SettingsPane;
pub use overlays::SettingsPaneAction;
pub use overlays::SettingsRenderOptions;
pub use pane::FocusedPane;
pub use pane::FrameworkFocusId;
pub use pane::FrameworkOverlayId;
pub use pane::Mode;
pub use pane::Pane;
pub use pane::PaneChrome;
pub use pane::PaneFocusState;
pub use pane::PaneRule;
pub use pane::PaneSelectionState;
pub use pane::PaneTitleCount;
pub use pane::PaneTitleGroup;
pub use pane::PopupFrame;
pub use pane::RenderFocus;
pub use pane::RuleTitle;
pub use pane::default_pane_chrome;
pub use pane::empty_pane_block;
pub use pane::pane_title;
pub use pane::prefixed_pane_title;
pub use pane::render_horizontal_rule;
pub use pane::render_rules;
pub use pane::selection_state;
pub use pane::selection_state_for;
pub use pane::selection_style;
pub use settings_store::LoadedSettings;
pub use settings_store::SettingCodecs;
pub use settings_store::SettingsError;
pub use settings_store::SettingsFileSpec;
pub use settings_store::SettingsRegistry;
pub use settings_store::SettingsRow;
pub(crate) use settings_store::SettingsRowKind;
pub(crate) use settings_store::SettingsRowPayload;
pub use settings_store::SettingsSection;
pub use settings_store::SettingsStore;
pub use settings_store::read_array;
pub use settings_store::read_bool;
pub use settings_store::read_float;
pub use settings_store::read_int;
pub use settings_store::read_string;
pub use settings_store::write_value;
pub use toasts::ReactivateOutcome;
pub use toasts::RunningTracker;
pub use toasts::ToastCommand;
pub use toasts::ToastDuration;
pub use toasts::ToastHit;
pub use toasts::ToastId;
pub(crate) use toasts::ToastPlacement;
pub use toasts::ToastSettings;
pub use toasts::ToastStyle;
pub use toasts::ToastTaskId;
pub use toasts::Toasts;
pub use toasts::ToastsRenderCtx;
pub use toasts::TrackedItem;
pub use toasts::TrackedItemKey;
pub use toasts::format_toast_items;
pub use toasts::toast_body_width;
pub use util::format_progressive;
pub use watched_file::WatchedFile;
